name: slang_flutter
description: Flutter support for slang. This library provides helpful Flutter API.
version: 4.12.1
repository: https://codeberg.org/Tienisto/slang
publish_to: none

environment:
  flutter: '>=3.19.0'
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  slang:
    git:
      url: https://github.com/iamtoricool/slang.git
      ref: stable
      path: slang

dev_dependencies:
  intl: any
  flutter_test:
    sdk: flutter
